Feature/#21
bookmaru/MARU-Android pull request #42
Opened 2021-05-12 13:31 UTC by sery270

<img width="531" alt="스크린샷 2021-05-12 오후 10 28 28" src="https://user-images.githubusercontent.com/59532818/117982852-63aeab80-b371-11eb-9218-31bb370db880.png">

- 위 두 화면 만듦
  - 두 화면 (SearchResultFragment)에 재사용할 SearchResultAdapter 구현
    - getItemViewType 오버라이딩, sealed class와 when 절 활용
  - 테스트해볼 localDS 작성 
  - SearchResultFragment의 viewType는 나중에 safeArgs의 값으로 초기화 되어, 두 화면을 분기시킬 변수임 (Int)

2021-05-12 15:10 UTC, l2hyunwoo requested changes
수고하셨습니당!

2021-05-12 15:10 UTC, l2hyunwoo commented on app/src/main/java/kr/co/marubook/presentation/search/SearchViewModel.kt
> +        }
runCatching 이용해서 error handling 하시는걸 추천드립니다.

```suggestion
        viewModelScope.launch {
            runCatching { searchRepository.getBookList() }
                .onSuccess { _bookList.value = it }
                .onFailure { it.printStackTrace() }
        }
```

2021-05-12 15:10 UTC, l2hyunwoo commented on app/src/main/java/kr/co/marubook/presentation/search/adapter/SearchResultAdapter.kt
> +            }
👍🏻

2021-05-12 15:10 UTC, l2hyunwoo commented on app/src/main/java/kr/co/marubook/presentation/search/adapter/SearchResultAdapter.kt
> +            DataBindingUtil.inflate(inflater, R.layout.item_book_result, parent, false)
굳이 두 가지 뷰를 모두 inflate하는 이유가 있을까? 적절한 뷰에 맞는 바인딩 객체만 만들면 되는거 아닐까요?

2021-05-13 01:57 UTC, sery270 commented on app/src/main/java/kr/co/marubook/data/repository/HomeRepositoryImpl.kt
> +        Log.d("getBookList", "$popularBookList")
got it 👌🏼

2021-05-13 01:59 UTC, sery270 commented on app/src/main/java/kr/co/marubook/domain/entity/SearchItem.kt
> +    }
수정하겠씀니다 👌🏼

2021-05-13 01:59 UTC, sery270 commented on app/src/main/java/kr/co/marubook/domain/entity/SearchItem.kt
> +    ) : SearchItem()
이건 몰랐네 감사합니다

2021-05-13 02:00 UTC, sery270 commented on app/src/main/java/kr/co/marubook/presentation/search/SearchResultFragment.kt
> +    private val viewType: Int = SearchItem.BookItem_TYPE
맞슴다 아래에 분기처리 해뒀고, 일단은 SearchItem.BookItem_TYPE를 디폴트 값으로 설정해둔 것입니다

2021-05-13 02:01 UTC, sery270 commented on app/src/main/java/kr/co/marubook/presentation/search/SearchResultFragment.kt
> +        super.onCreateView(inflater, container, savedInstanceState)
got it 👌🏼

2021-05-13 02:02 UTC, sery270 commented on app/src/main/java/kr/co/marubook/presentation/search/SearchViewModel.kt
> +        }
오 감사합니다 runCatching에 대해 잘모르는데 좀 더 공부해볼게요 ! (간단해보이지만)

2021-05-13 02:04 UTC, sery270 commented on app/src/main/java/kr/co/marubook/presentation/search/adapter/SearchResultAdapter.kt
> +            DataBindingUtil.inflate(inflater, R.layout.item_book_result, parent, false)
그렇네요 when절안에서 적정한 뷰에 대해서만 inflate해도 문제 없을 것 같아요 ! 이것도 수정해보겠습니다

2021-05-13 02:06 UTC, sery270 commented on app/src/main/java/kr/co/marubook/data/repository/HomeRepositoryImpl.kt
> +        Log.d("getBookList", "$popularBookList")
근데 이거 다시 보니 심지어 홈에 찍었네,, 죄송함다..ㅎ

2021-05-14 09:00 UTC, l2hyunwoo approved these changes

2021-05-14 14:33 UTC, sery270 commented on app/src/main/java/kr/co/marubook/data/model/ResponseRecentKeyword.kt
> +}
네엡 ><

2021-05-14 14:33 UTC, merged